Volokhina.ASP.NET/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Volokhina.ASP.NET.BLL.Interface;
using AutoMapper;
using Volokhina.ASP.NET.Entities;
using Volokhina.ASP.NET.BLL;
using Volokhina.ASP.NET.Models;

namespace Volokhina.ASP.NET.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeLogic _employeeLogic;

        private readonly IMapper _mapper;
        public EmployeeController()
        {
        }

        public EmployeeController(IEmployeeLogic employeeLogic, IMapper mapper)
        {
            _employeeLogic = employeeLogic;
            _mapper = mapper;
        }        

        public ActionResult AllEmployees()
        {
            var employees = _employeeLogic.GetAllEmployees();
            return View(_mapper.Map<List<EmployeeModel>>(employees));
        }

        public ActionResult AddEmployee(int idEmployee, string fullName, int age, string phoneNumber, string email, string address)
        {
            _employeeLogic.AddEmployee(new Employee(idEmployee, fullName, age, phoneNumber, email, address));
            return RedirectToAction("AllEmployees");
        }

        public ActionResult DeleteEmployee(int idEmployee)
        {
            _employeeLogic.DeleteEmployee(idEmployee);
            return RedirectToAction("AllEmployees");
        }        
    }
}

Volokhina.ASP.NET/Controllers/PositionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Volokhina.ASP.NET.BLL.Interface;
using Volokhina.ASP.NET.Models;
using Volokhina.ASP.NET.Entities;

namespace Volokhina.ASP.NET.Controllers
{
    public class PositionController : Controller
    {
        
        private readonly IPositionLogic _positionLogic;

        private readonly IMapper _mapper;

        public PositionController()
        {
        }

        public PositionController(IPositionLogic positionLogic, IMapper mapper)
        {
            _positionLogic = positionLogic;
            _mapper = mapper;
        }

        public ActionResult GetPosition(int idPosition)
        {
            TempData["IDPosition"] = idPosition;
            List<Position> positionList = _positionLogic.GetAllPositions().ToList().FindAll(p => p.IDPosition == idPosition);
            return View(_mapper.Map<List<PositionsModel>>(positionList));
        }

        public ActionResult AddPosition(int idPosition, string nameOfPosition)
        {
            _ = _positionLogic.AddPosition(new Position((int)TempData.Peek("IDPosition"), nameOfPosition));
            return RedirectToAction("GetPosition", new { idPosition = TempData.Peek("IDPosition") });
        }

        public ActionResult DeletePosition(int id)
        {
            _positionLogic.DeletePosition(id);
            return RedirectToAction("GetPosition", new { idPosition = TempData["IDPosition"] });
        }

        public ActionResult AllPositions()
        {
            var positions = _positionLogic.GetAllPositions();
            return View(_mapper.Map<List<PositionsModel>>(positions));
        }
    }
}

Volokhina.ASP.NET/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <span class="navbar-brand">
                Company
            </span>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        @Html.ActionLink("Exit", "Index", "Home", new { }, new { @class = "btn btn-success" })
                    </li>
                    <li class="nav-item active">
                        @Html.ActionLink("Home Page", "AllEmployees", "Employee", new { }, new { @class = "btn btn-success" })
                    </li>
                </ul>
                <span class="navbar-brand">
                    @Html.ActionLink("List", "AllPositions", "Position", new { }, new { @class = "btn btn-success" })
                </span>
                <span class="navbar-text">
                    Admin Profile
                </span>
            </div>
        </nav>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.2020</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Volokhina.ASP.NET/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <span class="navbar-brand">
                Company
            </span>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        @Html.ActionLink("Exit", "Index", "Home Page", new { }, new { @class = "btn btn-success" })
                    </li>
                </ul>
                <span class="navbar-text">
                    @TempData.Peek("login")
                </span>
            </div>
        </nav>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.2020</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>